VIA_ENABLE = yes

SWAP_HANDS_ENABLE     = no
AUTOCORRECT_ENABLE    = no
CAPS_WORD_ENABLE      = yes
CONSOLE_ENABLE        = no
KEYLOGGER_ENABLE      = no
WPM_ENABLE            = yes
OLED_ENABLE           = yes
ENCODER_MAP_ENABLE    = yes
PER_KEY_TAPPING       = no
NO_USB_STARTUP_CHECK  = yes
