// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/pwebb/qmk_firmware/keyboards/bastardkb/dilemma/4x6_4/ninja.jpg --output /home/pwebb/qmk_firmware/keyboards/bastardkb/dilemma/4x6_4/generated --format pal256 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_ninja_length;
extern const uint8_t  gfx_ninja[21363];
